//! Tests of the generated table in `confusables.rs`. They live here because that file is
//! written whole by `scripts/generate_confusables.py`: a test appended to it is lost the
//! next time it is generated.

use super::confusables::CONFUSABLES;

/// `confusables.rs` holds what the generator prints and nothing else: its six header
/// lines, one line per entry, and the closing bracket.
#[test]
fn the_generated_file_holds_only_what_the_generator_prints() {
    let text = include_str!("confusables.rs");
    let lines: Vec<&str> = text.lines().collect();
    assert_eq!(
        lines[0],
        "//! Latin look-alikes folded to ASCII: generated by `scripts/generate_confusables.py`"
    );
    assert!(
        lines[1].starts_with("//! from Unicode confusables.txt (UTS #39), version "),
        "{}",
        lines[1]
    );
    assert_eq!(
        lines[2],
        "//! Unicode data is under the Unicode License v3 (`Unicode-3.0`). Do not edit by hand."
    );
    assert_eq!(lines[3], "");
    assert_eq!(
        lines[4],
        "/// `(code point, ASCII letter)`, sorted by code point for a binary search."
    );
    assert_eq!(lines[5], "pub const CONFUSABLES: &[(char, char)] = &[");
    assert_eq!(lines.last(), Some(&"];"));
    let entries = &lines[6..lines.len() - 1];
    assert_eq!(entries.len(), CONFUSABLES.len());
    for (line, (source, letter)) in entries.iter().zip(CONFUSABLES) {
        assert_eq!(
            *line,
            format!("    ('\\u{{{:04X}}}', '{letter}'),", *source as u32)
        );
    }
    assert!(text.ends_with("];\n"), "text after the table");
}

/// Entries are in strictly increasing code-point order, as the binary search needs.
#[test]
fn confusables_are_sorted_by_code_point() {
    for i in 1..CONFUSABLES.len() {
        assert!(
            CONFUSABLES[i].0 as u32 > CONFUSABLES[i - 1].0 as u32,
            "not sorted at index {}: {:x} <= {:x}",
            i,
            CONFUSABLES[i].0 as u32,
            CONFUSABLES[i - 1].0 as u32,
        );
    }
}

/// Each ASCII target is a lowercase letter a-z.
#[test]
fn confusables_map_to_lowercase_ascii_letters() {
    for &(cp, mapped) in CONFUSABLES {
        assert!(
            mapped.is_ascii_lowercase(),
            "{:x} maps to '{}' which is not a-z",
            cp as u32,
            mapped
        );
        assert_ne!(cp, mapped, "{:?} maps to itself ({})", cp, mapped);
    }
}

/// The set contains entries for all 26 lowercase letters.
#[test]
fn confusables_cover_all_lowercase_letters() {
    let mapped: std::collections::HashSet<char> = CONFUSABLES.iter().map(|&(_, c)| c).collect();
    for letter in b'a'..=b'z' {
        assert!(
            mapped.contains(&(letter as char)),
            "no confusable maps to '{}'",
            letter as char
        );
    }
}
