#!/usr/bin/env python3
"""Generate src/guards/confusables.rs from Unicode's confusables.txt (UTS #39).

Keeps the entries `instruction-smuggling` needs to fold a look-alike word back to
ASCII: a single non-ASCII source code point, from a script that has Latin look-alikes,
whose prototype is a single ASCII letter. Sources that NFKC already maps (fullwidth,
mathematical alphanumerics) are left out, since the gate applies NFKC first.

Usage (offline; download the file first):
    python3 scripts/generate_confusables.py confusables.txt > src/guards/confusables.rs
"""
import sys
import unicodedata

# Blocks with Latin look-alikes: Latin-1 Supplement to IPA, Greek and Coptic, Cyrillic
# and its supplements, Armenian, Cherokee, Latin Extended Additional, Greek Extended,
# Letterlike Symbols, Latin Extended-C/D/E, Lisu.
RANGES = [
    (0x0080, 0x02AF),
    (0x0370, 0x03FF),
    (0x0400, 0x052F),
    (0x0530, 0x058F),
    (0x13A0, 0x13FF),
    (0x1C80, 0x1C8F),
    (0x1E00, 0x1EFF),
    (0x1F00, 0x1FFF),
    (0x2100, 0x214F),
    (0x2C60, 0x2C7F),
    (0x2DE0, 0x2DFF),
    (0xA4D0, 0xA4FF),
    (0xA640, 0xA69F),
    (0xA720, 0xA7FF),
    (0xAB30, 0xAB6F),
]


def main(path):
    version = date = "?"
    pairs = {}
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            if line.startswith("# Version:"):
                version = line.split(":", 1)[1].strip()
            if line.startswith("# Date:"):
                date = line.split(":", 1)[1].strip().split(",")[0]
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            src, dst, *_ = [x.strip() for x in body.split(";")]
            if " " in src or " " in dst:
                continue
            s, d = int(src, 16), int(dst, 16)
            if not any(lo <= s <= hi for lo, hi in RANGES):
                continue
            if not (0x41 <= d <= 0x5A or 0x61 <= d <= 0x7A):
                continue
            if unicodedata.normalize("NFKC", chr(s)) != chr(s):
                continue
            pairs[s] = chr(d).lower()
    out = [
        "//! Latin look-alikes folded to ASCII: generated by `scripts/generate_confusables.py`",
        f"//! from Unicode confusables.txt (UTS #39), version {version}, dated {date}.",
        "//! Unicode data is under the Unicode License v3 (`Unicode-3.0`). Do not edit by hand.",
        "",
        "/// `(code point, ASCII letter)`, sorted by code point for a binary search.",
        "pub const CONFUSABLES: &[(char, char)] = &[",
    ]
    for s in sorted(pairs):
        out.append(f"    ('\\u{{{s:04X}}}', '{pairs[s]}'),")
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
