#!/usr/bin/env python3
"""Generate the MacPorts Portfile for a tagged release.

A cargo port needs the checksums of the release's source tarball and of every
crate it vendors (`cargo.crates`). Both exist only once the tag does, so the
Portfile is generated by the release workflow and attached to the release,
like the Homebrew formula, instead of being hand-maintained in the tree.

Usage:
  generate_portfile.py --version 0.7.0 --tarball discipline-0.7.0.tar.gz \\
      --cargo-lock Cargo.lock --output Portfile
  generate_portfile.py --test
"""

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path


def crates(lock_text: str) -> list[tuple[str, str, str]]:
    """(name, version, sha256) of every registry crate in Cargo.lock; the root
    package and path dependencies carry no checksum and are not vendored."""
    out = []
    for block in lock_text.split("[[package]]")[1:]:
        fields = dict(re.findall(r'(?m)^(name|version|source|checksum) = "([^"]*)"', block))
        source = fields.get("source", "")
        if source.startswith("git+"):
            raise SystemExit(f"error: git dependency {fields.get('name')} cannot be vendored by the cargo PortGroup")
        if source.startswith("registry+") and "checksum" in fields:
            out.append((fields["name"], fields["version"], fields["checksum"]))
    return sorted(out)


def digest(path: Path) -> tuple[str, str, int]:
    data = path.read_bytes()
    return hashlib.new("ripemd160", data).hexdigest(), hashlib.sha256(data).hexdigest(), len(data)


def render(version: str, rmd160: str, sha256: str, size: int, crate_list: list[tuple[str, str, str]]) -> str:
    width = max((len(n) for n, _, _ in crate_list), default=0)
    vwidth = max((len(v) for _, v, _ in crate_list), default=0)
    crate_lines = " \\\n".join(
        f"                    {n:<{width}}  {v:<{vwidth}}  {c}" for n, v, c in crate_list
    )
    return f"""# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
# Generated by scripts/generate_portfile.py for v{version}; do not edit by hand.

PortSystem          1.0
PortGroup           github 1.0
PortGroup           cargo 1.0

github.setup        orieg discipline {version} v
github.tarball_from archive
revision            0

categories          devel
license             {{MIT Apache-2}}
maintainers         openmaintainer

description         CI/CD gatekeeper and AI coding agent diff sentinel
long_description    discipline checks a change against its merge base and rejects \\
                    weakened assertions, vacuous or deleted tests, unjustified unsafe \\
                    code and weakened CI configuration, using tree-sitter syntax trees.

homepage            https://orieg.github.io/discipline/

checksums           ${{distname}}${{extract.suffix}} \\
                        rmd160  {rmd160} \\
                        sha256  {sha256} \\
                        size    {size}

destroot {{
    xinstall -m 0755 ${{worksrcpath}}/target/[cargo.rust_platform]/release/${{name}} ${{destroot}}${{prefix}}/bin/
    xinstall -d ${{destroot}}${{prefix}}/share/man/man1 ${{destroot}}${{prefix}}/share/man/man5
    xinstall -m 0644 ${{worksrcpath}}/man/man1/discipline.1 ${{destroot}}${{prefix}}/share/man/man1/
    xinstall -m 0644 ${{worksrcpath}}/man/man5/discipline.toml.5 ${{destroot}}${{prefix}}/share/man/man5/
    xinstall -d ${{destroot}}${{prefix}}/share/zsh/site-functions ${{destroot}}${{prefix}}/share/bash-completion/completions ${{destroot}}${{prefix}}/share/fish/vendor_completions.d
    xinstall -m 0644 ${{worksrcpath}}/completions/_discipline ${{destroot}}${{prefix}}/share/zsh/site-functions/
    xinstall -m 0644 ${{worksrcpath}}/completions/discipline.bash ${{destroot}}${{prefix}}/share/bash-completion/completions/discipline
    xinstall -m 0644 ${{worksrcpath}}/completions/discipline.fish ${{destroot}}${{prefix}}/share/fish/vendor_completions.d/
}}

cargo.crates \\
{crate_lines}
"""


def self_test() -> None:
    lock = '''
[[package]]
name = "discipline"
version = "9.9.9"

[[package]]
name = "zeta"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aa"

[[package]]
name = "alpha"
version = "0.2.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb"
'''
    got = crates(lock)
    assert got == [("alpha", "0.2.0", "bb"), ("zeta", "1.0.0", "aa")], got
    try:
        crates(lock + '\n[[package]]\nname = "g"\nversion = "1"\nsource = "git+https://x"\n')
    except SystemExit:
        pass
    else:
        raise AssertionError("a git dependency must be an error")
    text = render("9.9.9", "r" * 40, "s" * 64, 123, got)
    assert "github.setup        orieg discipline 9.9.9 v" in text
    assert "sha256  " + "s" * 64 in text and "size    123" in text
    assert text.rstrip().endswith("zeta   1.0.0  aa"), text[-80:]
    assert "{" not in text.split("cargo.crates")[1], "unrendered braces"
    print("generate_portfile: self-test passed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version")
    parser.add_argument("--tarball", type=Path, help="the release's GitHub source archive")
    parser.add_argument("--cargo-lock", type=Path, default=Path("Cargo.lock"))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--test", action="store_true")
    args = parser.parse_args()
    if args.test:
        self_test()
        return
    if not (args.version and args.tarball and args.output):
        parser.error("--version, --tarball and --output are required")
    rmd160, sha256, size = digest(args.tarball)
    text = render(args.version, rmd160, sha256, size, crates(args.cargo_lock.read_text()))
    args.output.write_text(text)
    print(f"Generated Portfile (v{args.version}, {text.count(chr(10))} lines) at {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
