//! Grandfathering baseline mechanism for discipline findings.
//!
//! Allows teams adopting discipline on mature repositories to grandfather pre-existing
//! findings into `discipline-baseline.toml` using `discipline baseline --write`.
//! Subsequent runs report baselined findings as non-blocking notes ("N findings grandfathered by baseline in this gate (not blocking)")
//! and fail only on NEW violations.
//!
//! Fingerprints are stable and decoupled from line numbers. Version 2 (written since the
//! finding registry, `crate::findings`) is `sha256("v2:" + gate/code + ":" + path + ":" +
//! content_hash)`: the finding's code, never its title, so a reworded title keeps its
//! baseline, and the source line and the finding's anchor, never its message
//! ([`fingerprint_for_version`]). Version 1 used the title in place of the code; a version-1 file still matches
//! (with a deprecation note) until `discipline baseline --migrate` rewrites it.

use crate::cli::load_config;
use crate::config::Severity;
use crate::gitctx::GitCtx;
use crate::guards::{run_checks, Context, GateOutcome, Violation};
use crate::report::gitlab::sha256_hex;
use crate::style;
use anyhow::{bail, Context as _, Result};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};

pub const DEFAULT_BASELINE_FILE: &str = "discipline-baseline.toml";

/// The fingerprint version `discipline baseline` writes.
pub const FINGERPRINT_VERSION: u32 = 2;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct BaselineEntry {
    pub gate: String,
    pub rule: String,
    pub path: String,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DisciplineBaseline {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub findings: Vec<BaselineEntry>,
}

fn default_version() -> u32 {
    1
}

impl Default for DisciplineBaseline {
    fn default() -> Self {
        Self {
            version: FINGERPRINT_VERSION,
            findings: Vec::new(),
        }
    }
}

impl DisciplineBaseline {
    /// Reads the baseline at `path`, naming the file `shown` in an error (see
    /// [`path_for_message`]).
    pub fn load_from_file_named(path: impl AsRef<Path>, shown: &str) -> Result<Self> {
        let content = std::fs::read_to_string(path.as_ref())
            .with_context(|| format!("failed to read baseline file `{shown}`"))?;
        toml::from_str(&content).with_context(|| format!("failed to parse baseline file `{shown}`"))
    }

    /// Writes the baseline to `path`, naming the file `shown` in an error (see
    /// [`path_for_message`]).
    pub fn write_to_file(&self, path: impl AsRef<Path>, shown: &str) -> Result<()> {
        let path = path.as_ref();
        let mut sorted = self.clone();
        sorted.findings.sort();
        let serialized = toml::to_string_pretty(&sorted)
            .context("failed to serialize discipline baseline to TOML")?;
        let header = "# Discipline Findings Baseline\n# Generated by `discipline baseline --write`\n# Do not edit manually; commit alongside configuration changes.\n\n";
        let out = format!("{header}{serialized}");
        std::fs::write(path, out)
            .with_context(|| format!("failed to write baseline file `{shown}`"))?;
        Ok(())
    }
}

/// How a message names the file at `path`: relative to `root` and `/`-separated when the
/// file is inside it, as every other message names a file; by its file name alone when it
/// is outside, or reaches inside through `..`. The directory of a file outside the
/// repository is the runner's, and can be a user's home directory.
pub fn path_for_message(root: &Path, path: &Path) -> String {
    match path_in_repository(root, path) {
        Some(rel) => rel,
        None => match path.file_name() {
            Some(name) => name.to_string_lossy().into_owned(),
            None => "(a path outside the repository)".to_string(),
        },
    }
}

/// The path of `path` relative to `root`, `/`-separated, when the file is inside `root`
/// without going through `..`: the path git knows the file by. `None` for a file outside
/// the repository, which no side of a change holds.
pub fn path_in_repository(root: &Path, path: &Path) -> Option<String> {
    use std::path::Component;
    // A path given through a symlinked directory names the same file as its resolved
    // form, which is the form `root` has.
    let resolved = path.canonicalize().ok();
    let rel = path
        .strip_prefix(root)
        .ok()
        .or_else(|| resolved.as_deref().and_then(|p| p.strip_prefix(root).ok()))?;
    let inside = rel.components().next().is_some()
        && rel.components().all(|c| matches!(c, Component::Normal(_)));
    inside.then(|| {
        rel.components()
            .map(|c| c.as_os_str().to_string_lossy())
            .collect::<Vec<_>>()
            .join("/")
    })
}

/// Which findings `discipline baseline` records.
///
/// A baseline exists to let a blocking finding through. A finding that never
/// blocks (a `note`, or a `warning` without `fail_on_warnings`) buys nothing
/// by being grandfathered and only adds bulk and stale-entry churn, so the
/// default records exactly the findings that would fail `check` under the same
/// configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RecordPolicy {
    /// `check` would treat warnings as failures.
    pub fail_on_warnings: bool,
    /// Record every severity regardless (for a consumer that intends to
    /// tighten severities later).
    pub all_severities: bool,
}

impl RecordPolicy {
    pub fn records(&self, severity: Severity) -> bool {
        self.all_severities
            || match severity {
                Severity::Error => true,
                Severity::Warning => self.fail_on_warnings,
                Severity::Note => false,
            }
    }
}

/// Per-severity, per-gate counts of findings, for the recorded/skipped report.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SeverityTally {
    /// Indexed error, warning, note: the order the report prints them in.
    by_severity: [BTreeMap<String, usize>; 3],
}

const SEVERITY_ORDER: [Severity; 3] = [Severity::Error, Severity::Warning, Severity::Note];

fn severity_index(severity: Severity) -> usize {
    match severity {
        Severity::Error => 0,
        Severity::Warning => 1,
        Severity::Note => 2,
    }
}

impl SeverityTally {
    pub fn add(&mut self, severity: Severity, gate: &str) {
        *self.by_severity[severity_index(severity)]
            .entry(gate.to_string())
            .or_insert(0) += 1;
    }

    pub fn total(&self) -> usize {
        self.by_severity.iter().flat_map(|g| g.values()).sum()
    }

    /// `1 error, 2 warnings`, or `none`.
    pub fn summary(&self) -> String {
        self.render(false)
    }

    /// `2 warnings (agent-diff: 1, pii: 1), 1 note (pii: 1)`, or `none`.
    pub fn summary_by_gate(&self) -> String {
        self.render(true)
    }

    fn render(&self, with_gates: bool) -> String {
        let parts: Vec<String> = self
            .by_severity
            .iter()
            .zip(SEVERITY_ORDER)
            .filter(|(gates, _)| !gates.is_empty())
            .map(|(gates, sev)| {
                let n: usize = gates.values().sum();
                let plural = if n == 1 { "" } else { "s" };
                let mut s = format!("{n} {sev}{plural}");
                if with_gates {
                    let g = gates
                        .iter()
                        .map(|(gate, c)| format!("{gate}: {c}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    s.push_str(&format!(" ({g})"));
                }
                s
            })
            .collect();
        if parts.is_empty() {
            "none".to_string()
        } else {
            parts.join(", ")
        }
    }
}

/// The version-2 fingerprint of a finding, reading source lines through `read_file`.
pub fn compute_violation_fingerprint_with_content<F>(v: &Violation, read_file: F) -> String
where
    F: Fn(&str) -> Option<String>,
{
    fingerprint_for_version(v, read_file, FINGERPRINT_VERSION)
}

/// The trimmed source line a finding is on, and which occurrence of that line in its file
/// it is on, counted from 1 over the lines above it that are identical once trimmed.
/// `None` when the finding has no line or the line cannot be read.
fn line_and_occurrence<F>(v: &Violation, read_file: F) -> Option<(String, usize)>
where
    F: Fn(&str) -> Option<String>,
{
    let (file, line) = (v.file.as_deref()?, v.line.filter(|l| *l > 0)?);
    let content = read_file(file)?;
    let own = content.lines().nth(line - 1)?.trim();
    let above = content
        .lines()
        .take(line - 1)
        .filter(|l| l.trim() == own)
        .count();
    Some((own.to_string(), above + 1))
}

/// What [`line_and_occurrence`] answers for a finding on each line of `content`, the
/// entry of a line at its number less one.
fn lines_and_occurrences(content: &str) -> Vec<(String, usize)> {
    let mut seen: HashMap<&str, usize> = HashMap::new();
    content
        .lines()
        .map(|line| {
            crate::ast::ancestry::count(1);
            let own = line.trim();
            let occurrence = seen.entry(own).or_insert(0);
            *occurrence += 1;
            (own.to_string(), *occurrence)
        })
        .collect()
}

/// What tells a finding on the `occurrence`-th of several identical lines from the one
/// on the first: nothing for the first, so a finding on a line that does not repeat, or
/// on the first of those that do, keeps the fingerprint it always had. A finding with an
/// anchor is told apart by the anchor.
fn occurrence_suffix(v: &Violation, occurrence: usize) -> String {
    if occurrence > 1 && v.anchor.is_none() {
        format!("\noccurrence:{occurrence}")
    } else {
        String::new()
    }
}

/// The fingerprint of a finding under a given baseline version: 1 keys on the title, 2 on
/// the code.
///
/// What is hashed besides the code and path: the trimmed source line when the finding has
/// one that can be read, and in version 2 the finding's anchor ([`Violation::anchor`], a
/// typed source datum) with it, or, with no anchor, the line's occurrence number when it
/// is not the first of its text in the file ([`line_and_occurrence`]). With no line,
/// version 2 hashes the anchor alone, or nothing when there is none, so a reworded
/// message never changes a fingerprint; version 1 hashed the message.
pub fn fingerprint_for_version<F>(v: &Violation, read_file: F, version: u32) -> String
where
    F: Fn(&str) -> Option<String>,
{
    let located = line_and_occurrence(v, read_file);
    fingerprint_of(v, located.as_ref().map(|(l, n)| (l.as_str(), *n)), version)
}

/// [`fingerprint_for_version`] for a finding whose line and occurrence are known.
fn fingerprint_of(v: &Violation, located: Option<(&str, usize)>, version: u32) -> String {
    let path = v.file.as_deref().unwrap_or("");
    let content = match (located, version >= 2, &v.anchor) {
        // The anchor goes in with the line: two tests reported at identical lines (an
        // `@Test` attribute) stay apart.
        (Some((line, _)), true, Some(a)) => format!("{line}\nanchor:{a}"),
        (Some((line, n)), true, None) => format!("{line}{}", occurrence_suffix(v, n)),
        (Some((line, _)), false, _) => line.to_string(),
        (None, true, Some(a)) => format!("anchor:{a}"),
        (None, true, None) => String::new(),
        (None, false, _) => v.message.trim().to_string(),
    };

    let content_hash = sha256_hex(content.as_bytes());
    let source = if version >= 2 {
        format!("v2:{}:{}:{}", v.code, path, content_hash)
    } else {
        let title = v.legacy_title.as_deref().unwrap_or(&v.title);
        format!("{}:{}:{}:{}", v.gate, title, path, content_hash)
    };
    sha256_hex(source.as_bytes())
}

/// The fingerprint two findings that share one fall back to: their messages, and the
/// occurrence number of their line as in [`fingerprint_of`].
fn message_fingerprint(v: &Violation, occurrence: usize) -> String {
    let source = format!(
        "v2:{}:{}:{}",
        v.code,
        v.file.as_deref().unwrap_or(""),
        sha256_hex(
            format!(
                "message:{}{}",
                v.message.trim(),
                occurrence_suffix(v, occurrence)
            )
            .as_bytes()
        )
    );
    sha256_hex(source.as_bytes())
}

/// The lines of the files the findings of a run are in, each file read once: what
/// [`line_and_occurrence`] answers for a finding, without reading its file and counting
/// the lines above it again for each finding in the file.
struct FileLines<F> {
    read_file: F,
    /// The lines of a file, by its path; `None` for a file that cannot be read.
    lines_of: std::cell::RefCell<HashMap<String, Option<Lines>>>,
}

/// The lines of one file, as [`lines_and_occurrences`] lists them.
type Lines = Vec<(String, usize)>;

impl<F> FileLines<F>
where
    F: Fn(&str) -> Option<String>,
{
    fn new(read_file: F) -> Self {
        Self {
            read_file,
            lines_of: Default::default(),
        }
    }

    /// The trimmed line `v` is on and which occurrence of it that is.
    fn located(&self, v: &Violation) -> Option<(String, usize)> {
        let (file, line) = (v.file.as_deref()?, v.line.filter(|l| *l > 0)?);
        self.lines_of
            .borrow_mut()
            .entry(file.to_string())
            .or_insert_with(|| {
                (self.read_file)(file).map(|content| lines_and_occurrences(&content))
            })
            .as_ref()
            .and_then(|lines| lines.get(line - 1).cloned())
    }
}

/// For a finding on a later occurrence of a repeated line: the occurrence number, and the
/// fingerprint the finding would have on the first occurrence. A baseline written before
/// occurrences were told apart recorded every occurrence under that one fingerprint, one
/// entry each. `None` for a first occurrence, an anchored finding, or a fingerprint that
/// is not built from the line. `located` is the finding's line and its occurrence
/// ([`line_and_occurrence`]).
fn first_occurrence_twin(
    v: &Violation,
    located: Option<(String, usize)>,
) -> Option<(usize, String)> {
    let (line, occurrence) = located?;
    if occurrence < 2 || v.anchor.is_some() {
        return None;
    }
    if v.fingerprint == fingerprint_of(v, Some((&line, occurrence)), FINGERPRINT_VERSION) {
        Some((
            occurrence,
            fingerprint_of(v, Some((&line, 1)), FINGERPRINT_VERSION),
        ))
    } else if v.fingerprint == message_fingerprint(v, occurrence) {
        Some((occurrence, message_fingerprint(v, 1)))
    } else {
        None
    }
}

/// Version-2 fingerprints for every finding of a run. Two findings with no line and no
/// anchor, of one code in one file, would share a fingerprint, so baselining one would
/// hide the other: those fall back to hashing their messages. A code that can repeat in
/// a file without a line needs an anchor; debug builds (every test) stop on one that has
/// none.
pub fn fill_fingerprints<F>(violations: &mut [&mut Violation], read_file: F)
where
    F: Fn(&str) -> Option<String>,
{
    let collided = fingerprint_all(violations, read_file);
    debug_assert!(
        collided.is_empty(),
        "{} repeats in `{}` with no line and no anchor: give it an anchor (GateOutcome::anchor_last)",
        collided
            .iter()
            .map(|(code, _)| format!("`{code}`"))
            .collect::<Vec<_>>()
            .join(", "),
        collided.first().map(|(_, f)| f.as_str()).unwrap_or("")
    );
}

/// [`fill_fingerprints`] without the test-build stop: returns the `(code, path)` of each
/// group that fell back to its messages.
fn fingerprint_all<F>(violations: &mut [&mut Violation], read_file: F) -> Vec<(String, String)>
where
    F: Fn(&str) -> Option<String>,
{
    let mut groups: HashMap<String, Vec<usize>> = HashMap::new();
    let mut occurrences = Vec::with_capacity(violations.len());
    // The lines of each file a finding is in, read once: reading the file and counting
    // the lines above for each finding read a file once for each finding in it.
    let lines = FileLines::new(read_file);
    for (i, v) in violations.iter_mut().enumerate() {
        let located = lines.located(v);
        v.fingerprint = fingerprint_of(
            v,
            located.as_ref().map(|(l, n)| (l.as_str(), *n)),
            FINGERPRINT_VERSION,
        );
        occurrences.push(located.map_or(1, |(_, n)| n));
        groups.entry(v.fingerprint.clone()).or_default().push(i);
    }
    let mut collided = Vec::new();
    for idx in groups.into_values().filter(|g| g.len() > 1) {
        let distinct: std::collections::HashSet<&str> = idx
            .iter()
            .map(|&i| violations[i].message.as_str())
            .collect();
        if distinct.len() < 2 {
            continue;
        }
        // Two hits on one line (`2 weeks, target Q2`) have distinct messages: the
        // message fallback below keeps them apart, and it is stable. Only a repeat with
        // no line is a missing anchor.
        if violations[idx[0]].line.is_none() {
            collided.push((
                violations[idx[0]].code.clone(),
                violations[idx[0]].file.clone().unwrap_or_default(),
            ));
        }
        for &i in &idx {
            violations[i].fingerprint = message_fingerprint(violations[i], occurrences[i]);
        }
    }
    collided
}

/// A baseline entry for a finding, in the current version.
pub fn entry_for<F>(v: &Violation, read_file: F) -> BaselineEntry
where
    F: Fn(&str) -> Option<String>,
{
    BaselineEntry {
        gate: v.gate.to_string(),
        rule: v.code.clone(),
        path: v.file.clone().unwrap_or_default(),
        // The run's own fingerprint when it has one: it carries the collision fallback
        // of `fill_fingerprints`.
        fingerprint: if v.fingerprint.is_empty() {
            compute_violation_fingerprint_with_content(v, read_file)
        } else {
            v.fingerprint.clone()
        },
    }
}

/// What `discipline baseline --migrate` did.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Migration {
    /// Version-1 entries rewritten to version 2.
    pub migrated: usize,
    /// Version-1 entries no current finding matches: already stale, and dropped.
    pub dropped: usize,
}

/// Rewrite a version-1 baseline to version 2: each entry that a current finding still
/// matches (under the version-1 formula) becomes that finding's version-2 entry. Entries
/// nothing matches are stale and are dropped, so the migrated baseline never grows.
pub fn migrate<F>(
    v1: &DisciplineBaseline,
    findings: &[&Violation],
    read_file: F,
) -> (DisciplineBaseline, Migration)
where
    F: Fn(&str) -> Option<String>,
{
    let mut available: HashMap<&str, usize> = HashMap::new();
    for e in &v1.findings {
        *available.entry(e.fingerprint.as_str()).or_insert(0) += 1;
    }
    let mut out = Vec::new();
    for v in findings {
        let old = fingerprint_for_version(v, &read_file, 1);
        if let Some(n) = available.get_mut(old.as_str()).filter(|n| **n > 0) {
            *n -= 1;
            out.push(entry_for(v, &read_file));
        }
    }
    out.sort();
    let report = Migration {
        migrated: out.len(),
        dropped: v1.findings.len() - out.len(),
    };
    (
        DisciplineBaseline {
            version: FINGERPRINT_VERSION,
            findings: out,
        },
        report,
    )
}

/// Compute a stable finding fingerprint decoupled from line numbers.
///
/// Formula: sha256(gate + ":" + rule + ":" + path + ":" + sha256(normalized_line_content))
pub fn compute_violation_fingerprint(repo_root: &Path, v: &Violation) -> String {
    compute_violation_fingerprint_with_content(v, |f| {
        let full_path = repo_root.join(f);
        std::fs::read_to_string(&full_path).ok()
    })
}

#[derive(Debug, Default)]
pub struct BaselineMatchResult {
    pub baselined_count: usize,
    pub stale_count: usize,
}

/// Match detected violations against the baseline using repository root path.
pub fn apply_baseline(
    repo_root: &Path,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult {
    apply_baseline_with_reader(
        |f| {
            let full_path = repo_root.join(f);
            std::fs::read_to_string(&full_path).ok()
        },
        baseline,
        outcomes,
    )
}

/// Match detected violations against the baseline using GitCtx (supports staged index blobs).
pub fn apply_baseline_with_git(
    git: &crate::gitctx::GitCtx,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> anyhow::Result<BaselineMatchResult> {
    let reads = crate::gitctx::ReadRecorder::new();
    let matched = apply_baseline_with_reader(reads.head(git), baseline, outcomes);
    reads.finish()?;
    Ok(matched)
}

/// Match detected violations against the baseline with custom line reader.
pub fn apply_baseline_with_reader<F>(
    read_file: F,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult
where
    F: Fn(&str) -> Option<String>,
{
    let mut available_fps: HashMap<String, usize> = HashMap::new();
    for entry in &baseline.findings {
        *available_fps.entry(entry.fingerprint.clone()).or_insert(0) += 1;
    }

    let recorded = available_fps.clone();

    let mut total_baselined = 0;
    let mut matched_by_entry: HashMap<String, usize> = HashMap::new();
    // A finding the baseline does not hold under its own fingerprint is looked for
    // under another, made from its line: the file is read once for all of them.
    let lines = FileLines::new(read_file);

    for outcome in outcomes.iter_mut() {
        if !outcome.enabled {
            continue;
        }

        let mut remaining_violations = Vec::with_capacity(outcome.violations.len());
        let mut gate_baselined = 0;

        for v in outcome.violations.drain(..) {
            let fp = if baseline.version >= FINGERPRINT_VERSION && !v.fingerprint.is_empty() {
                v.fingerprint.clone()
            } else {
                let located = lines.located(&v);
                fingerprint_of(
                    &v,
                    located.as_ref().map(|(l, n)| (l.as_str(), *n)),
                    baseline.version,
                )
            };
            // An entry recorded before occurrences of a repeated line were told apart
            // carries the first occurrence's fingerprint: `n` such entries accept the
            // first `n` occurrences, wherever this run reports them.
            let recorded_as_first = || {
                if baseline.version < FINGERPRINT_VERSION {
                    return None;
                }
                let (occurrence, first) = first_occurrence_twin(&v, lines.located(&v))?;
                (recorded.get(&first).copied().unwrap_or(0) >= occurrence).then_some(first)
            };
            let matched = if available_fps.get(&fp).is_some_and(|n| *n > 0) {
                Some(fp)
            } else {
                recorded_as_first().filter(|first| available_fps.get(first).is_some_and(|n| *n > 0))
            };
            if let Some(entry) = matched {
                if let Some(count) = available_fps.get_mut(&entry) {
                    *count -= 1;
                }
                *matched_by_entry.entry(entry).or_insert(0) += 1;
                gate_baselined += 1;
                total_baselined += 1;
                continue;
            }
            remaining_violations.push(v);
        }

        outcome.violations = remaining_violations;
        outcome.baselined = gate_baselined;

        if gate_baselined > 0 {
            let suffix = if gate_baselined == 1 { "" } else { "s" };
            outcome.notes.push(format!(
                "{gate_baselined} finding{suffix} grandfathered by baseline in this gate (not blocking)"
            ));
        }
    }

    let mut stale_count = 0;
    let mut stale_entries_by_gate: BTreeMap<String, Vec<&BaselineEntry>> = BTreeMap::new();

    let mut consumed_fps = matched_by_entry;
    for entry in &baseline.findings {
        if let Some(count) = consumed_fps.get_mut(&entry.fingerprint) {
            if *count > 0 {
                *count -= 1;
                continue;
            }
        }
        stale_count += 1;
        stale_entries_by_gate
            .entry(entry.gate.clone())
            .or_default()
            .push(entry);
    }

    for (gate, entries) in &stale_entries_by_gate {
        if let Some(outcome) = outcomes.iter_mut().find(|o| o.gate == *gate) {
            if !outcome.enabled {
                continue;
            }
            let count = entries.len();
            let suffix = if count == 1 { "y" } else { "ies" };
            let sample = entries
                .iter()
                .take(2)
                .map(|e| {
                    if e.path.is_empty() {
                        format!("`{}`", e.rule)
                    } else {
                        format!("`{}` in `{}`", e.rule, e.path)
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            let sample_str = if sample.is_empty() {
                String::new()
            } else if count > 2 {
                format!(" (e.g. {sample}, ...)")
            } else {
                format!(" ({sample})")
            };
            outcome.notes.push(format!(
                "{count} stale baseline entr{suffix} (resolved findings){sample_str}: run `discipline baseline --write` to ratchet down"
            ));
        }
    }

    BaselineMatchResult {
        baselined_count: total_baselined,
        stale_count,
    }
}

/// The `discipline baseline` subcommand.
pub fn run_cli(mut args: crate::cli::BaselineArgs) -> Result<bool> {
    // The base detection and the gates read the event payload, as in `check`.
    crate::gitctx::try_event_payload()?;
    if args.baseline_file == std::path::Path::new(crate::baseline::DEFAULT_BASELINE_FILE) {
        if let Some(p) = std::env::var("DISCIPLINE_BASELINE")
            .ok()
            .filter(|s| !s.trim().is_empty())
            .map(PathBuf::from)
        {
            args.baseline_file = p;
        }
    }
    if args.trust_workspace {
        std::env::set_var("DISCIPLINE_TRUST_WORKSPACE", "1");
    }
    let git = if args.whole_tree || args.migrate {
        GitCtx::open_whole_tree()?
    } else {
        let base_ref = crate::gitctx::detect_base_ref(args.base.as_deref(), None, None);
        GitCtx::open(&base_ref, false)?
    };
    let (config, config_path) = load_config(&args.config, Some(git.root()), None, None)?;
    // How every message of this command names the file: its path in the repository, or
    // its file name alone when it is outside (the directory is then the runner's).
    let baseline_path = git.root().join(&args.baseline_file);
    let baseline_shown = crate::baseline::path_for_message(git.root(), &baseline_path);
    let existing_baseline = if baseline_path.exists() {
        // An unreadable baseline is not an empty one: rewriting it would drop entries.
        Some(
            crate::baseline::DisciplineBaseline::load_from_file_named(
                &baseline_path,
                &baseline_shown,
            )
            .with_context(|| {
                format!(
                    "existing baseline `{baseline_shown}` could not be read; fix or remove it first"
                )
            })?,
        )
    } else {
        None
    };
    if args.migrate {
        let Some(old) = existing_baseline.as_ref() else {
            // No file is nothing to migrate, not an error: adoption scripts run this unconditionally.
            println!(
                "{} no baseline at `{}`; nothing to migrate.",
                style::yellow("note:"),
                baseline_shown
            );
            return Ok(true);
        };
        if old.version >= crate::baseline::FINGERPRINT_VERSION {
            println!(
                "`{}` already uses fingerprint version {}; nothing to migrate.",
                baseline_shown, old.version
            );
            return Ok(true);
        }
    } else if args.write
        && args.suite != crate::cli::SuiteChoice::All
        && existing_baseline
            .as_ref()
            .is_some_and(|b| b.version < crate::baseline::FINGERPRINT_VERSION)
    {
        bail!(
            "`{}` uses fingerprint version 1; run `discipline baseline --migrate` before writing part of it with --suite",
            baseline_shown
        );
    }

    let commits = git.commits()?;
    let (directives, directive_notes) =
        crate::tokens::extract_directives_for_config(None, &commits, &config);

    let ctx = Context {
        config: &config,
        head_config: None,
        git: &git,
        config_path: &config_path,
        baseline_path: None,
        baseline: None,
        staged: false,
        pr_title: None,
        pr_body: None,
        directives,
        directive_notes,
        bench_provenance: None,
        allow_cross_host_bench: false,
        bench_base_file: None,
        bench_head_file: None,
        test_base_report: None,
        test_head_report: None,
        test_report: None,
        forge: None,
    };

    let summary = run_checks(&config, args.suite, &ctx)?;

    let reads = crate::gitctx::ReadRecorder::new();
    let read_head = reads.head(&git);

    if args.migrate {
        let old = existing_baseline.expect("checked above");
        let findings: Vec<&crate::guards::Violation> = summary
            .outcomes
            .iter()
            .filter(|o| o.enabled)
            .flat_map(|o| &o.violations)
            .collect();
        let (migrated, report) = crate::baseline::migrate(&old, &findings, &read_head);
        reads.finish()?;
        migrated.write_to_file(&baseline_path, &baseline_shown)?;
        println!(
            "{} rewrote {} to fingerprint version {}: {} entr{} migrated, {} stale entr{} dropped",
            style::green("ok:"),
            baseline_shown,
            migrated.version,
            report.migrated,
            if report.migrated == 1 { "y" } else { "ies" },
            report.dropped,
            if report.dropped == 1 { "y" } else { "ies" },
        );
        println!(
            "Commit it in a change of its own: `config-integrity` accepts a migration that changes nothing but the baseline."
        );
        return Ok(true);
    }

    let mut entries = Vec::new();
    let examined_gates: std::collections::HashSet<&str> =
        summary.outcomes.iter().map(|o| o.gate).collect();

    // Preserve existing findings for gates that were not examined in this run (e.g. when --suite was passed)
    if let Some(existing) = existing_baseline {
        for entry in existing.findings {
            if !examined_gates.contains(entry.gate.as_str()) {
                entries.push(entry);
            }
        }
    }

    let policy = crate::baseline::RecordPolicy {
        fail_on_warnings: args.fail_on_warnings,
        all_severities: args.all_severities,
    };
    let mut recorded = crate::baseline::SeverityTally::default();
    let mut skipped = crate::baseline::SeverityTally::default();

    for o in &summary.outcomes {
        if !o.enabled {
            continue;
        }
        for v in &o.violations {
            if !policy.records(v.severity) {
                skipped.add(v.severity, v.gate);
                continue;
            }
            recorded.add(v.severity, v.gate);
            entries.push(crate::baseline::entry_for(v, &read_head));
        }
    }

    reads.finish()?;
    entries.sort();

    let baseline_obj = crate::baseline::DisciplineBaseline {
        version: crate::baseline::FINGERPRINT_VERSION,
        findings: entries,
    };

    // Nothing disappears silently: say what was left out and how to include it.
    let breakdown = {
        let mut b = format!(
            "  recorded: {}\n  skipped: {}",
            recorded.summary(),
            skipped.summary_by_gate()
        );
        if skipped.total() > 0 {
            b.push_str(if policy.fail_on_warnings {
                "\n  (notes never block; pass --all-severities to record them anyway)"
            } else {
                "\n  (non-blocking under the current configuration; pass --all-severities to record them, \
                 or --fail-on-warnings if `check` runs with it)"
            });
        }
        b
    };

    if args.write {
        baseline_obj.write_to_file(&baseline_path, &baseline_shown)?;
        println!(
            "{} recorded {} grandfathered finding{} to {}",
            style::green("ok:"),
            baseline_obj.findings.len(),
            if baseline_obj.findings.len() == 1 {
                ""
            } else {
                "s"
            },
            baseline_shown
        );
        println!("{breakdown}");
        if !baseline_obj.findings.is_empty() {
            println!(
                "\nTo commit this baseline under `config-integrity`, include this directive on its own line in the commit message or PR body:\n  allow-gate-weakening: baseline initial grandfathered baseline"
            );
        }
        Ok(true)
    } else {
        println!(
            "Found {} finding{} eligible for grandfathering.",
            baseline_obj.findings.len(),
            if baseline_obj.findings.len() == 1 {
                ""
            } else {
                "s"
            }
        );
        println!("{breakdown}");
        println!(
            "Run `discipline baseline --write` to record them to {}.",
            baseline_shown
        );
        Ok(true)
    }
}

#[cfg(test)]
mod tests {

    fn finding(title: &str, code: &str) -> Violation {
        Violation {
            gate: "unsafe-safety-comment",
            code: code.to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: title.to_string(),
            file: Some("src/lib.rs".to_string()),
            line: None,
            message: "unsafe block".to_string(),
            remediation: None,
        }
    }

    #[test]
    fn a_line_less_finding_is_keyed_by_its_anchor_never_its_message() {
        let none = |_: &str| None;
        let anchored = |anchor: &str, message: &str| Violation {
            anchor: Some(anchor.to_string()),
            message: message.to_string(),
            ..finding("t", "deletion-rationale/test-removed-without-rationale")
        };
        let one = anchored("test_one", "Test `test_one` was removed.");
        // A reworded message keeps the fingerprint; another anchor changes it.
        assert_eq!(
            fingerprint_for_version(&one, none, 2),
            fingerprint_for_version(&anchored("test_one", "`test_one` is gone."), none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&one, none, 2),
            fingerprint_for_version(
                &anchored("test_two", "Test `test_one` was removed."),
                none,
                2
            )
        );
        // No anchor: version 2 hashes nothing past the path, version 1 the message.
        let plain = finding("t", "c/x");
        let reworded = Violation {
            message: "reworded".into(),
            ..finding("t", "c/x")
        };
        assert_eq!(
            fingerprint_for_version(&plain, none, 2),
            fingerprint_for_version(&reworded, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&plain, none, 1),
            fingerprint_for_version(&reworded, none, 1)
        );
        // Identical source lines stay apart by their anchors.
        let read = |_: &str| Some("@Test\n@Test\n".to_string());
        let at = |line, anchor: &str| Violation {
            line: Some(line),
            ..anchored(anchor, "m")
        };
        assert_ne!(
            fingerprint_for_version(&at(1, "a"), read, 2),
            fingerprint_for_version(&at(2, "b"), read, 2)
        );
        assert_eq!(
            fingerprint_for_version(&at(1, "a"), read, 1),
            fingerprint_for_version(&at(2, "b"), read, 1),
            "version 1 is unchanged"
        );
    }

    /// Anchoring a kind changes its version-2 fingerprint and nothing about version 1: a
    /// version-1 baseline keeps matching, with or without a readable line.
    #[test]
    fn an_anchor_never_changes_a_version_one_fingerprint() {
        let none = |_: &str| None;
        let read = |_: &str| Some("  let x = danger();  \n".to_string());
        for line in [None, Some(1)] {
            let plain = Violation {
                line,
                ..finding("Old Title", "gate/code")
            };
            let anchored = Violation {
                anchor: Some("job:lint".to_string()),
                ..plain.clone()
            };
            assert_eq!(
                fingerprint_for_version(&plain, read, 1),
                fingerprint_for_version(&anchored, read, 1),
                "line {line:?}"
            );
            assert_eq!(
                fingerprint_for_version(&plain, none, 1),
                fingerprint_for_version(&anchored, none, 1),
                "line {line:?}, unreadable"
            );
            assert_ne!(
                fingerprint_for_version(&plain, read, 2),
                fingerprint_for_version(&anchored, read, 2),
                "line {line:?}: version 2 does hash the anchor"
            );
        }
        // The version-1 formula itself: gate, title, path and the hash of the message
        // (no line) or of the trimmed source line.
        let anchored = Violation {
            anchor: Some("job:lint".to_string()),
            ..finding("Old Title", "gate/code")
        };
        let v1 = |content: &str| {
            sha256_hex(
                format!(
                    "unsafe-safety-comment:Old Title:src/lib.rs:{}",
                    sha256_hex(content.as_bytes())
                )
                .as_bytes(),
            )
        };
        assert_eq!(
            fingerprint_for_version(&anchored, none, 1),
            v1("unsafe block")
        );
        let at_line = Violation {
            line: Some(1),
            ..anchored
        };
        assert_eq!(
            fingerprint_for_version(&at_line, read, 1),
            v1("let x = danger();")
        );
    }

    #[test]
    fn colliding_findings_fall_back_to_their_messages() {
        let mut a = finding("t", "c/x");
        let mut b = Violation {
            message: "another".into(),
            ..finding("t", "c/x")
        };
        let mut same = finding("t", "c/y");
        let mut dup = finding("t", "c/y");
        let collided = fingerprint_all(&mut [&mut a, &mut b, &mut same, &mut dup], |_| None);
        assert_eq!(
            collided,
            vec![("c/x".to_string(), "src/lib.rs".to_string())]
        );
        assert_ne!(
            a.fingerprint, b.fingerprint,
            "baselining one must not hide the other"
        );
        // Identical findings are one finding reported twice: nothing to separate.
        assert_eq!(same.fingerprint, dup.fingerprint);
    }

    /// Two unanchored line-less findings of one code in one file fall back to their
    /// messages, so baselining one never hides the other; a test build stops on it.
    #[test]
    #[should_panic(expected = "repeats in `src/lib.rs` with no line and no anchor")]
    fn unanchored_repeats_are_caught_in_a_test_build() {
        let mut a = finding("t", "c/x");
        let mut b = Violation {
            message: "another".into(),
            ..finding("t", "c/x")
        };
        fill_fingerprints(&mut [&mut a, &mut b], |_| None);
    }

    /// Two hits on one line (`2 weeks, target Q2`) are kept apart by their messages
    /// and are not a missing anchor.
    #[test]
    fn two_findings_on_one_line_are_separated_without_an_anchor() {
        let mut a = Violation {
            line: Some(3),
            ..finding("t", "c/x")
        };
        let mut b = Violation {
            line: Some(3),
            message: "another".into(),
            ..finding("t", "c/x")
        };
        fill_fingerprints(&mut [&mut a, &mut b], |_| Some("x\ny\nz\n".to_string()));
        assert_ne!(a.fingerprint, b.fingerprint);
    }

    /// Two hits on each of two identical lines are four findings: the message keeps the
    /// two of a line apart, the occurrence the two lines, and the first line's keep the
    /// fingerprints they have with no second line.
    #[test]
    fn two_hits_on_each_of_two_identical_lines_have_four_fingerprints() {
        let hit = |line, message: &str| Violation {
            line: Some(line),
            message: message.into(),
            ..finding("t", "c/x")
        };
        let prints = |content: &'static str, lines: &[usize]| {
            let mut found: Vec<Violation> = lines
                .iter()
                .flat_map(|l| [hit(*l, "first hit"), hit(*l, "second hit")])
                .collect();
            fill_fingerprints(&mut found.iter_mut().collect::<Vec<_>>(), |_| {
                Some(content.to_string())
            });
            found.into_iter().map(|v| v.fingerprint).collect::<Vec<_>>()
        };
        let both = prints("a, b\nother\na, b\n", &[1, 3]);
        let distinct: std::collections::HashSet<&String> = both.iter().collect();
        assert_eq!(distinct.len(), 4, "{both:?}");
        assert_eq!(both[..2], prints("a, b\nother\n", &[1])[..]);
    }

    /// The findings of one run, in files of lines that repeat, of lines that do not, with
    /// a line past the end of its file and a file that cannot be read.
    fn findings_in(files: usize, lines: usize) -> Vec<Violation> {
        let mut found = Vec::new();
        for file in 0..files {
            for line in 1..=lines + 1 {
                found.push(Violation {
                    file: Some(format!("src/f{file}.rs")),
                    line: Some(line),
                    ..finding("t", "c/x")
                });
            }
        }
        found.push(Violation {
            file: Some("src/gone.rs".to_string()),
            line: Some(3),
            ..finding("t", "c/x")
        });
        found
    }

    /// The content of `src/f<n>.rs`: every third line is one text, the others differ by
    /// their number and by the file.
    fn content_of(path: &str, lines: usize) -> Option<String> {
        let file = path.strip_prefix("src/f")?.strip_suffix(".rs")?;
        Some(
            (0..lines)
                .map(|i| {
                    if i % 3 == 0 {
                        "    same();\n".to_string()
                    } else {
                        format!("  line {i} of {file}\n")
                    }
                })
                .collect(),
        )
    }

    /// The fingerprint a run gives each finding is the one the finding has read alone:
    /// the file read once for the run answers as the file read for the finding does.
    #[test]
    fn the_findings_of_a_run_have_the_fingerprints_they_have_alone() {
        let mut found = findings_in(3, 30);
        let reads = std::cell::Cell::new(0);
        fill_fingerprints(&mut found.iter_mut().collect::<Vec<_>>(), |path| {
            reads.set(reads.get() + 1);
            content_of(path, 30)
        });
        for v in &found {
            assert_eq!(
                v.fingerprint,
                compute_violation_fingerprint_with_content(v, |path| content_of(path, 30)),
                "{:?} line {:?}",
                v.file,
                v.line
            );
        }
        // The lines that repeat are told apart, so every finding has its own.
        let distinct: std::collections::HashSet<&String> =
            found.iter().map(|v| &v.fingerprint).collect();
        assert_eq!(distinct.len(), found.len());
    }

    /// The findings of one file cost steps in proportion to their number, and the file
    /// is read once. Before #672 the file was read for each finding, and its lines
    /// above the finding counted again for each.
    #[test]
    fn the_findings_of_one_file_cost_steps_in_proportion_to_their_number() {
        let steps_of = |lines: usize| -> (u64, usize) {
            let mut found = findings_in(1, lines);
            let reads = std::cell::Cell::new(0);
            let ((), counted) = crate::ast::ancestry::steps(|| {
                fill_fingerprints(&mut found.iter_mut().collect::<Vec<_>>(), |path| {
                    reads.set(reads.get() + 1);
                    content_of(path, lines)
                })
            });
            (counted, reads.get())
        };
        let ((few, read_few), (many, read_many)) = (steps_of(40), steps_of(160));
        assert!(
            few > 0 && many < 5 * few,
            "{few} steps for 40, {many} for 160"
        );
        // The file of the findings, and the one that cannot be read.
        assert_eq!((read_few, read_many), (2, 2));
    }

    /// The findings of one file left after a baseline of `entries` (version 2) is
    /// applied, by line; how many times a file was read; and the steps counted.
    fn left_after(lines: usize, entries: Vec<String>) -> (Vec<usize>, usize, u64) {
        let mut found = findings_in(1, lines);
        fill_fingerprints(&mut found.iter_mut().collect::<Vec<_>>(), |path| {
            content_of(path, lines)
        });
        let mut out = GateOutcome::new("unsafe-safety-comment");
        out.violations = found;
        let baseline = DisciplineBaseline {
            version: 2,
            findings: entries
                .into_iter()
                .map(|fingerprint| BaselineEntry {
                    gate: "unsafe-safety-comment".to_string(),
                    rule: "c/x".to_string(),
                    path: "src/f0.rs".to_string(),
                    fingerprint,
                })
                .collect(),
        };
        let mut outcomes = vec![out];
        let reads = std::cell::Cell::new(0);
        let ((), counted) = crate::ast::ancestry::steps(|| {
            apply_baseline_with_reader(
                |path| {
                    reads.set(reads.get() + 1);
                    content_of(path, lines)
                },
                &baseline,
                &mut outcomes,
            );
        });
        (
            outcomes[0]
                .violations
                .iter()
                .filter_map(|v| v.line)
                .collect(),
            reads.get(),
            counted,
        )
    }

    /// A finding a baseline does not hold under its own fingerprint is looked for under
    /// the one its line has on its first occurrence, and the file is read once for all
    /// of them. Before #672 it was read for each finding, and its lines above the
    /// finding counted again for each.
    #[test]
    fn findings_a_baseline_does_not_hold_are_looked_up_with_their_file_read_once() {
        // `same();` stands on every third line, from the first. A baseline written
        // before occurrences were told apart holds the first one's fingerprint once
        // for each of the first three.
        let first = compute_violation_fingerprint_with_content(
            &Violation {
                file: Some("src/f0.rs".to_string()),
                line: Some(1),
                ..finding("t", "c/x")
            },
            |path| content_of(path, 30),
        );
        let (left, reads, _) = left_after(30, vec![first.clone(), first.clone(), first.clone()]);
        // Lines 1, 4 and 7 are accepted, the later occurrences and every other line
        // are not; the line past the end and the file that cannot be read stay.
        let wanted: Vec<usize> = (1..=31)
            .filter(|l| ![1, 4, 7].contains(l))
            .chain([3])
            .collect();
        assert_eq!(left, wanted);
        // The file of the findings, and the one that cannot be read.
        assert_eq!(reads, 2);
        let ((_, read_few, few), (_, read_many, many)) = (
            left_after(40, vec![first.clone()]),
            left_after(160, vec![first]),
        );
        assert_eq!((read_few, read_many), (2, 2));
        assert!(
            few > 0 && many < 5 * few,
            "{few} steps for 40, {many} for 160"
        );
    }

    #[test]
    fn version_two_keys_on_the_code_and_version_one_on_the_title() {
        let none = |_: &str| None;
        let a = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let renamed = finding(
            "SAFETY Comment Missing",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let recoded = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/other",
        );
        assert_eq!(
            fingerprint_for_version(&a, none, 2),
            fingerprint_for_version(&renamed, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 2),
            fingerprint_for_version(&recoded, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 1),
            fingerprint_for_version(&renamed, none, 1)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 1),
            fingerprint_for_version(&a, none, 2)
        );
    }

    #[test]
    fn a_renamed_finding_keeps_its_version_one_fingerprint() {
        let none = |_: &str| None;
        let old = finding("Test Newly Skipped", "ignored-tests/existing-test-skipped");
        let mut renamed = finding(
            "Existing Test Skipped",
            "ignored-tests/existing-test-skipped",
        );
        renamed.legacy_title = Some("Test Newly Skipped".into());
        assert_eq!(
            fingerprint_for_version(&old, none, 1),
            fingerprint_for_version(&renamed, none, 1)
        );
    }

    #[test]
    fn migration_keeps_matched_entries_and_drops_stale_ones() {
        let none = |_: &str| None;
        let live = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let v1 = DisciplineBaseline {
            version: 1,
            findings: vec![
                BaselineEntry {
                    gate: "unsafe-safety-comment".into(),
                    rule: live.title.clone(),
                    path: "src/lib.rs".into(),
                    fingerprint: fingerprint_for_version(&live, none, 1),
                },
                BaselineEntry {
                    gate: "unsafe-safety-comment".into(),
                    rule: live.title.clone(),
                    path: "src/gone.rs".into(),
                    fingerprint: "0".repeat(64),
                },
            ],
        };
        let (v2, report) = migrate(&v1, &[&live], none);
        assert_eq!(
            report,
            Migration {
                migrated: 1,
                dropped: 1
            }
        );
        assert_eq!(v2.version, FINGERPRINT_VERSION);
        assert_eq!(v2.findings, vec![entry_for(&live, none)]);
        assert_eq!(v2.findings[0].rule, live.code);
    }

    use super::*;

    #[test]
    fn a_message_names_a_file_inside_the_root_by_its_relative_path() {
        let root = Path::new("/work/repo");
        let shown = |p: &str| path_for_message(root, Path::new(p));
        assert_eq!(
            shown("/work/repo/discipline-baseline.toml"),
            "discipline-baseline.toml"
        );
        assert_eq!(shown("/work/repo/policy/known.toml"), "policy/known.toml");
        // Outside the root, or inside only by way of `..`: the file name alone.
        assert_eq!(shown("/elsewhere/known.toml"), "known.toml");
        assert_eq!(shown("/work/repo/../known.toml"), "known.toml");
        assert_eq!(shown("/work/repo"), "repo");
    }

    #[test]
    fn a_message_names_a_file_outside_the_root_by_its_file_name_alone() {
        let root = Path::new("/work/repo");
        let shown = |p: &str| path_for_message(root, Path::new(p));
        assert_eq!(shown("/elsewhere/of/someone/known.toml"), "known.toml");
        assert_eq!(shown("/work/repo/../known.toml"), "known.toml");
        assert_eq!(shown("/work/repository/known.toml"), "known.toml");
        // No file name to print: nothing of the path is.
        assert_eq!(shown("/work/repo/.."), "(a path outside the repository)");
        assert_eq!(shown("/"), "(a path outside the repository)");
        // Control: inside the root the relative path is kept whole.
        assert_eq!(shown("/work/repo/policy/known.toml"), "policy/known.toml");
    }

    #[test]
    fn record_policy_follows_what_would_block() {
        let default = RecordPolicy {
            fail_on_warnings: false,
            all_severities: false,
        };
        assert!(default.records(Severity::Error));
        assert!(!default.records(Severity::Warning));
        assert!(!default.records(Severity::Note));

        let strict = RecordPolicy {
            fail_on_warnings: true,
            all_severities: false,
        };
        assert!(strict.records(Severity::Error));
        assert!(strict.records(Severity::Warning));
        assert!(!strict.records(Severity::Note));

        let all = RecordPolicy {
            fail_on_warnings: false,
            all_severities: true,
        };
        assert!(all.records(Severity::Warning));
        assert!(all.records(Severity::Note));
    }

    #[test]
    fn severity_tally_renders_in_severity_order_with_gates() {
        let mut t = SeverityTally::default();
        assert_eq!(t.summary(), "none");
        t.add(Severity::Note, "pii");
        t.add(Severity::Warning, "pii");
        t.add(Severity::Warning, "agent-diff");
        t.add(Severity::Error, "time-estimates");
        assert_eq!(t.total(), 4);
        assert_eq!(t.summary(), "1 error, 2 warnings, 1 note");
        assert_eq!(
            t.summary_by_gate(),
            "1 error (time-estimates: 1), 2 warnings (agent-diff: 1, pii: 1), 1 note (pii: 1)"
        );
    }

    #[test]
    fn test_baseline_roundtrip() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("discipline-baseline.toml");

        let baseline = DisciplineBaseline {
            version: 1,
            findings: vec![BaselineEntry {
                gate: "time-estimates".to_string(),
                rule: "Time Estimates In Documentation".to_string(),
                path: "docs/ROADMAP.md".to_string(),
                fingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
                    .to_string(),
            }],
        };

        baseline.write_to_file(&path, "b.toml").unwrap();
        // A file that cannot be written is named as the caller shows it, never by `path`.
        let missing = path.parent().unwrap().join("no-such-dir").join("b.toml");
        let shown = format!(
            "{:#}",
            baseline.write_to_file(&missing, "b.toml").unwrap_err()
        );
        assert!(
            shown.starts_with("failed to write baseline file `b.toml`"),
            "{shown}"
        );
        assert!(!shown.contains("no-such-dir"), "{shown}");
        let loaded = DisciplineBaseline::load_from_file_named(&path, "b.toml").unwrap();
        assert_eq!(baseline, loaded);
    }

    #[test]
    fn test_fingerprint_is_line_number_independent() {
        let temp = tempfile::tempdir().unwrap();
        let file_path = temp.path().join("sample.txt");
        std::fs::write(&file_path, "\n\n   sample target line content   \n").unwrap();

        let v1 = Violation {
            gate: "pii",
            code: "pii/fixture".to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(3),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp1 = compute_violation_fingerprint(temp.path(), &v1);

        // Edit file: add 5 lines before the content
        std::fs::write(&file_path, "# Header\n# Line 2\n# Line 3\n# Line 4\n# Line 5\n\n\n   sample target line content   \n").unwrap();

        let v2 = Violation {
            gate: "pii",
            code: "pii/fixture".to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(8),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp2 = compute_violation_fingerprint(temp.path(), &v2);

        // Line number shifted from 3 to 8, but fingerprint MUST match exactly
        assert_eq!(fp1, fp2);
    }
}
