//! Grandfathering baseline mechanism for discipline findings.
//!
//! Allows teams adopting discipline on mature repositories to grandfather pre-existing
//! findings into `discipline-baseline.toml` using `discipline baseline --write`.
//! Subsequent runs report baselined findings as non-blocking notes ("N findings grandfathered by baseline in this gate (not blocking)")
//! and fail only on NEW violations.
//!
//! Fingerprints are stable and decoupled from line numbers. Version 2 (written since the
//! finding registry, `crate::findings`) is `sha256("v2:" + gate/code + ":" + path + ":" +
//! content_hash)`: the finding's code, never its title, so a reworded title keeps its
//! baseline, and the source line and the finding's anchor, never its message
//! ([`fingerprint_for_version`]). Version 1 used the title in place of the code; a version-1 file still matches
//! (with a deprecation note) until `discipline baseline --migrate` rewrites it.

use crate::config::Severity;
use crate::guards::{GateOutcome, Violation};
use crate::report::gitlab::sha256_hex;
use anyhow::{Context as _, Result};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

pub const DEFAULT_BASELINE_FILE: &str = "discipline-baseline.toml";

/// The fingerprint version `discipline baseline` writes.
pub const FINGERPRINT_VERSION: u32 = 2;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct BaselineEntry {
    pub gate: String,
    pub rule: String,
    pub path: String,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DisciplineBaseline {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub findings: Vec<BaselineEntry>,
}

fn default_version() -> u32 {
    1
}

impl Default for DisciplineBaseline {
    fn default() -> Self {
        Self {
            version: FINGERPRINT_VERSION,
            findings: Vec::new(),
        }
    }
}

impl DisciplineBaseline {
    pub fn load_from_file(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read baseline file `{}`", path.display()))?;
        toml::from_str(&content)
            .with_context(|| format!("failed to parse baseline file `{}`", path.display()))
    }

    pub fn write_to_file(&self, path: impl AsRef<Path>) -> Result<()> {
        let path = path.as_ref();
        let mut sorted = self.clone();
        sorted.findings.sort();
        let serialized = toml::to_string_pretty(&sorted)
            .context("failed to serialize discipline baseline to TOML")?;
        let header = "# Discipline Findings Baseline\n# Generated by `discipline baseline --write`\n# Do not edit manually; commit alongside configuration changes.\n\n";
        let out = format!("{header}{serialized}");
        std::fs::write(path, out)
            .with_context(|| format!("failed to write baseline file `{}`", path.display()))?;
        Ok(())
    }
}

/// Which findings `discipline baseline` records.
///
/// A baseline exists to let a blocking finding through. A finding that never
/// blocks (a `note`, or a `warning` without `fail_on_warnings`) buys nothing
/// by being grandfathered and only adds bulk and stale-entry churn, so the
/// default records exactly the findings that would fail `check` under the same
/// configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RecordPolicy {
    /// `check` would treat warnings as failures.
    pub fail_on_warnings: bool,
    /// Record every severity regardless (for a consumer that intends to
    /// tighten severities later).
    pub all_severities: bool,
}

impl RecordPolicy {
    pub fn records(&self, severity: Severity) -> bool {
        self.all_severities
            || match severity {
                Severity::Error => true,
                Severity::Warning => self.fail_on_warnings,
                Severity::Note => false,
            }
    }
}

/// Per-severity, per-gate counts of findings, for the recorded/skipped report.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SeverityTally {
    /// Indexed error, warning, note: the order the report prints them in.
    by_severity: [BTreeMap<String, usize>; 3],
}

const SEVERITY_ORDER: [Severity; 3] = [Severity::Error, Severity::Warning, Severity::Note];

fn severity_index(severity: Severity) -> usize {
    match severity {
        Severity::Error => 0,
        Severity::Warning => 1,
        Severity::Note => 2,
    }
}

impl SeverityTally {
    pub fn add(&mut self, severity: Severity, gate: &str) {
        *self.by_severity[severity_index(severity)]
            .entry(gate.to_string())
            .or_insert(0) += 1;
    }

    pub fn total(&self) -> usize {
        self.by_severity.iter().flat_map(|g| g.values()).sum()
    }

    /// `1 error, 2 warnings`, or `none`.
    pub fn summary(&self) -> String {
        self.render(false)
    }

    /// `2 warnings (agent-diff: 1, pii: 1), 1 note (pii: 1)`, or `none`.
    pub fn summary_by_gate(&self) -> String {
        self.render(true)
    }

    fn render(&self, with_gates: bool) -> String {
        let parts: Vec<String> = self
            .by_severity
            .iter()
            .zip(SEVERITY_ORDER)
            .filter(|(gates, _)| !gates.is_empty())
            .map(|(gates, sev)| {
                let n: usize = gates.values().sum();
                let plural = if n == 1 { "" } else { "s" };
                let mut s = format!("{n} {sev}{plural}");
                if with_gates {
                    let g = gates
                        .iter()
                        .map(|(gate, c)| format!("{gate}: {c}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    s.push_str(&format!(" ({g})"));
                }
                s
            })
            .collect();
        if parts.is_empty() {
            "none".to_string()
        } else {
            parts.join(", ")
        }
    }
}

/// The version-2 fingerprint of a finding, reading source lines through `read_file`.
pub fn compute_violation_fingerprint_with_content<F>(v: &Violation, read_file: F) -> String
where
    F: Fn(&str) -> Option<String>,
{
    fingerprint_for_version(v, read_file, FINGERPRINT_VERSION)
}

/// The fingerprint of a finding under a given baseline version: 1 keys on the title, 2 on
/// the code.
///
/// What is hashed besides the code and path: the trimmed source line when the finding has
/// one that can be read, and in version 2 the finding's anchor ([`Violation::anchor`], a
/// typed source datum) with it. With no line, version 2 hashes the anchor alone, or
/// nothing when there is none, so a reworded message never changes a fingerprint;
/// version 1 hashed the message.
pub fn fingerprint_for_version<F>(v: &Violation, read_file: F, version: u32) -> String
where
    F: Fn(&str) -> Option<String>,
{
    let path = v.file.as_deref().unwrap_or("");
    let source_line = match (&v.file, v.line) {
        (Some(f), Some(l)) if l > 0 => {
            read_file(f).and_then(|c| c.lines().nth(l - 1).map(|s| s.trim().to_string()))
        }
        _ => None,
    };
    let content = match (source_line, version >= 2, &v.anchor) {
        // The anchor goes in with the line: two tests reported at identical lines (an
        // `@Test` attribute) stay apart.
        (Some(line), true, Some(a)) => format!("{line}\nanchor:{a}"),
        (Some(line), _, _) => line,
        (None, true, Some(a)) => format!("anchor:{a}"),
        (None, true, None) => String::new(),
        (None, false, _) => v.message.trim().to_string(),
    };

    let content_hash = sha256_hex(content.as_bytes());
    let source = if version >= 2 {
        format!("v2:{}:{}:{}", v.code, path, content_hash)
    } else {
        let title = v.legacy_title.as_deref().unwrap_or(&v.title);
        format!("{}:{}:{}:{}", v.gate, title, path, content_hash)
    };
    sha256_hex(source.as_bytes())
}

/// Version-2 fingerprints for every finding of a run. Two findings with no line and no
/// anchor, of one code in one file, would share a fingerprint, so baselining one would
/// hide the other: those fall back to hashing their messages. A code that can repeat in
/// a file without a line needs an anchor; debug builds (every test) stop on one that has
/// none.
pub fn fill_fingerprints<F>(violations: &mut [&mut Violation], read_file: F)
where
    F: Fn(&str) -> Option<String>,
{
    let collided = fingerprint_all(violations, read_file);
    debug_assert!(
        collided.is_empty(),
        "{} repeats in `{}` with no line and no anchor: give it an anchor (GateOutcome::anchor_last)",
        collided
            .iter()
            .map(|(code, _)| format!("`{code}`"))
            .collect::<Vec<_>>()
            .join(", "),
        collided.first().map(|(_, f)| f.as_str()).unwrap_or("")
    );
}

/// [`fill_fingerprints`] without the test-build stop: returns the `(code, path)` of each
/// group that fell back to its messages.
fn fingerprint_all<F>(violations: &mut [&mut Violation], read_file: F) -> Vec<(String, String)>
where
    F: Fn(&str) -> Option<String>,
{
    let mut groups: HashMap<String, Vec<usize>> = HashMap::new();
    for (i, v) in violations.iter_mut().enumerate() {
        v.fingerprint = fingerprint_for_version(v, &read_file, FINGERPRINT_VERSION);
        groups.entry(v.fingerprint.clone()).or_default().push(i);
    }
    let mut collided = Vec::new();
    for idx in groups.into_values().filter(|g| g.len() > 1) {
        let distinct: std::collections::HashSet<&str> = idx
            .iter()
            .map(|&i| violations[i].message.as_str())
            .collect();
        if distinct.len() < 2 {
            continue;
        }
        collided.push((
            violations[idx[0]].code.clone(),
            violations[idx[0]].file.clone().unwrap_or_default(),
        ));
        for &i in &idx {
            let v = &mut *violations[i];
            let source = format!(
                "v2:{}:{}:{}",
                v.code,
                v.file.as_deref().unwrap_or(""),
                sha256_hex(format!("message:{}", v.message.trim()).as_bytes())
            );
            v.fingerprint = sha256_hex(source.as_bytes());
        }
    }
    collided
}

/// A baseline entry for a finding, in the current version.
pub fn entry_for<F>(v: &Violation, read_file: F) -> BaselineEntry
where
    F: Fn(&str) -> Option<String>,
{
    BaselineEntry {
        gate: v.gate.to_string(),
        rule: v.code.clone(),
        path: v.file.clone().unwrap_or_default(),
        // The run's own fingerprint when it has one: it carries the collision fallback
        // of `fill_fingerprints`.
        fingerprint: if v.fingerprint.is_empty() {
            compute_violation_fingerprint_with_content(v, read_file)
        } else {
            v.fingerprint.clone()
        },
    }
}

/// What `discipline baseline --migrate` did.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Migration {
    /// Version-1 entries rewritten to version 2.
    pub migrated: usize,
    /// Version-1 entries no current finding matches: already stale, and dropped.
    pub dropped: usize,
}

/// Rewrite a version-1 baseline to version 2: each entry that a current finding still
/// matches (under the version-1 formula) becomes that finding's version-2 entry. Entries
/// nothing matches are stale and are dropped, so the migrated baseline never grows.
pub fn migrate<F>(
    v1: &DisciplineBaseline,
    findings: &[&Violation],
    read_file: F,
) -> (DisciplineBaseline, Migration)
where
    F: Fn(&str) -> Option<String>,
{
    let mut available: HashMap<&str, usize> = HashMap::new();
    for e in &v1.findings {
        *available.entry(e.fingerprint.as_str()).or_insert(0) += 1;
    }
    let mut out = Vec::new();
    for v in findings {
        let old = fingerprint_for_version(v, &read_file, 1);
        if let Some(n) = available.get_mut(old.as_str()).filter(|n| **n > 0) {
            *n -= 1;
            out.push(entry_for(v, &read_file));
        }
    }
    out.sort();
    let report = Migration {
        migrated: out.len(),
        dropped: v1.findings.len() - out.len(),
    };
    (
        DisciplineBaseline {
            version: FINGERPRINT_VERSION,
            findings: out,
        },
        report,
    )
}

/// Compute a stable finding fingerprint decoupled from line numbers.
///
/// Formula: sha256(gate + ":" + rule + ":" + path + ":" + sha256(normalized_line_content))
pub fn compute_violation_fingerprint(repo_root: &Path, v: &Violation) -> String {
    compute_violation_fingerprint_with_content(v, |f| {
        let full_path = repo_root.join(f);
        std::fs::read_to_string(&full_path).ok()
    })
}

#[derive(Debug, Default)]
pub struct BaselineMatchResult {
    pub baselined_count: usize,
    pub stale_count: usize,
    pub stale_by_gate: BTreeMap<String, usize>,
}

/// Match detected violations against the baseline using repository root path.
pub fn apply_baseline(
    repo_root: &Path,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult {
    apply_baseline_with_reader(
        |f| {
            let full_path = repo_root.join(f);
            std::fs::read_to_string(&full_path).ok()
        },
        baseline,
        outcomes,
    )
}

/// Match detected violations against the baseline using GitCtx (supports staged index blobs).
pub fn apply_baseline_with_git(
    git: &crate::gitctx::GitCtx,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult {
    apply_baseline_with_reader(|f| git.head_content(f).ok().flatten(), baseline, outcomes)
}

/// Match detected violations against the baseline with custom line reader.
pub fn apply_baseline_with_reader<F>(
    read_file: F,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult
where
    F: Fn(&str) -> Option<String>,
{
    let mut available_fps: HashMap<String, usize> = HashMap::new();
    for entry in &baseline.findings {
        *available_fps.entry(entry.fingerprint.clone()).or_insert(0) += 1;
    }

    let mut total_baselined = 0;
    let mut matched_by_entry: HashMap<String, usize> = HashMap::new();

    for outcome in outcomes.iter_mut() {
        if !outcome.enabled {
            continue;
        }

        let mut remaining_violations = Vec::with_capacity(outcome.violations.len());
        let mut gate_baselined = 0;

        for v in outcome.violations.drain(..) {
            let fp = if baseline.version >= FINGERPRINT_VERSION && !v.fingerprint.is_empty() {
                v.fingerprint.clone()
            } else {
                fingerprint_for_version(&v, &read_file, baseline.version)
            };
            if let Some(count) = available_fps.get_mut(&fp) {
                if *count > 0 {
                    *count -= 1;
                    *matched_by_entry.entry(fp).or_insert(0) += 1;
                    gate_baselined += 1;
                    total_baselined += 1;
                    continue;
                }
            }
            remaining_violations.push(v);
        }

        outcome.violations = remaining_violations;
        outcome.baselined = gate_baselined;

        if gate_baselined > 0 {
            let suffix = if gate_baselined == 1 { "" } else { "s" };
            outcome.notes.push(format!(
                "{gate_baselined} finding{suffix} grandfathered by baseline in this gate (not blocking)"
            ));
        }
    }

    let mut stale_count = 0;
    let mut stale_entries_by_gate: BTreeMap<String, Vec<&BaselineEntry>> = BTreeMap::new();

    let mut consumed_fps = matched_by_entry;
    for entry in &baseline.findings {
        if let Some(count) = consumed_fps.get_mut(&entry.fingerprint) {
            if *count > 0 {
                *count -= 1;
                continue;
            }
        }
        stale_count += 1;
        stale_entries_by_gate
            .entry(entry.gate.clone())
            .or_default()
            .push(entry);
    }

    let mut stale_by_gate: BTreeMap<String, usize> = BTreeMap::new();
    for (gate, entries) in &stale_entries_by_gate {
        stale_by_gate.insert(gate.clone(), entries.len());
        if let Some(outcome) = outcomes.iter_mut().find(|o| o.gate == *gate) {
            if !outcome.enabled {
                continue;
            }
            let count = entries.len();
            let suffix = if count == 1 { "y" } else { "ies" };
            let sample = entries
                .iter()
                .take(2)
                .map(|e| {
                    if e.path.is_empty() {
                        format!("`{}`", e.rule)
                    } else {
                        format!("`{}` in `{}`", e.rule, e.path)
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            let sample_str = if sample.is_empty() {
                String::new()
            } else if count > 2 {
                format!(" (e.g. {sample}, ...)")
            } else {
                format!(" ({sample})")
            };
            outcome.notes.push(format!(
                "{count} stale baseline entr{suffix} (resolved findings){sample_str}: run `discipline baseline --write` to ratchet down"
            ));
        }
    }

    BaselineMatchResult {
        baselined_count: total_baselined,
        stale_count,
        stale_by_gate,
    }
}

#[cfg(test)]
mod tests {

    fn finding(title: &str, code: &str) -> Violation {
        Violation {
            gate: "unsafe-safety-comment",
            code: code.to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: title.to_string(),
            file: Some("src/lib.rs".to_string()),
            line: None,
            message: "unsafe block".to_string(),
            remediation: None,
        }
    }

    #[test]
    fn a_line_less_finding_is_keyed_by_its_anchor_never_its_message() {
        let none = |_: &str| None;
        let anchored = |anchor: &str, message: &str| Violation {
            anchor: Some(anchor.to_string()),
            message: message.to_string(),
            ..finding("t", "deletion-rationale/test-removed-without-rationale")
        };
        let one = anchored("test_one", "Test `test_one` was removed.");
        // A reworded message keeps the fingerprint; another anchor changes it.
        assert_eq!(
            fingerprint_for_version(&one, none, 2),
            fingerprint_for_version(&anchored("test_one", "`test_one` is gone."), none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&one, none, 2),
            fingerprint_for_version(
                &anchored("test_two", "Test `test_one` was removed."),
                none,
                2
            )
        );
        // No anchor: version 2 hashes nothing past the path, version 1 the message.
        let plain = finding("t", "c/x");
        let reworded = Violation {
            message: "reworded".into(),
            ..finding("t", "c/x")
        };
        assert_eq!(
            fingerprint_for_version(&plain, none, 2),
            fingerprint_for_version(&reworded, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&plain, none, 1),
            fingerprint_for_version(&reworded, none, 1)
        );
        // Identical source lines stay apart by their anchors.
        let read = |_: &str| Some("@Test\n@Test\n".to_string());
        let at = |line, anchor: &str| Violation {
            line: Some(line),
            ..anchored(anchor, "m")
        };
        assert_ne!(
            fingerprint_for_version(&at(1, "a"), read, 2),
            fingerprint_for_version(&at(2, "b"), read, 2)
        );
        assert_eq!(
            fingerprint_for_version(&at(1, "a"), read, 1),
            fingerprint_for_version(&at(2, "b"), read, 1),
            "version 1 is unchanged"
        );
    }

    #[test]
    fn colliding_findings_fall_back_to_their_messages() {
        let mut a = finding("t", "c/x");
        let mut b = Violation {
            message: "another".into(),
            ..finding("t", "c/x")
        };
        let mut same = finding("t", "c/y");
        let mut dup = finding("t", "c/y");
        let collided = fingerprint_all(&mut [&mut a, &mut b, &mut same, &mut dup], |_| None);
        assert_eq!(
            collided,
            vec![("c/x".to_string(), "src/lib.rs".to_string())]
        );
        assert_ne!(
            a.fingerprint, b.fingerprint,
            "baselining one must not hide the other"
        );
        // Identical findings are one finding reported twice: nothing to separate.
        assert_eq!(same.fingerprint, dup.fingerprint);
    }

    /// Two unanchored line-less findings of one code in one file fall back to their
    /// messages, so baselining one never hides the other; a test build stops on it.
    #[test]
    #[should_panic(expected = "repeats in `src/lib.rs` with no line and no anchor")]
    fn unanchored_repeats_are_caught_in_a_test_build() {
        let mut a = finding("t", "c/x");
        let mut b = Violation {
            message: "another".into(),
            ..finding("t", "c/x")
        };
        fill_fingerprints(&mut [&mut a, &mut b], |_| None);
    }

    #[test]
    fn version_two_keys_on_the_code_and_version_one_on_the_title() {
        let none = |_: &str| None;
        let a = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let renamed = finding(
            "SAFETY Comment Missing",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let recoded = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/other",
        );
        assert_eq!(
            fingerprint_for_version(&a, none, 2),
            fingerprint_for_version(&renamed, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 2),
            fingerprint_for_version(&recoded, none, 2)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 1),
            fingerprint_for_version(&renamed, none, 1)
        );
        assert_ne!(
            fingerprint_for_version(&a, none, 1),
            fingerprint_for_version(&a, none, 2)
        );
    }

    #[test]
    fn a_renamed_finding_keeps_its_version_one_fingerprint() {
        let none = |_: &str| None;
        let old = finding("Test Newly Skipped", "ignored-tests/existing-test-skipped");
        let mut renamed = finding(
            "Existing Test Skipped",
            "ignored-tests/existing-test-skipped",
        );
        renamed.legacy_title = Some("Test Newly Skipped".into());
        assert_eq!(
            fingerprint_for_version(&old, none, 1),
            fingerprint_for_version(&renamed, none, 1)
        );
    }

    #[test]
    fn migration_keeps_matched_entries_and_drops_stale_ones() {
        let none = |_: &str| None;
        let live = finding(
            "Unsafe Without SAFETY Comment",
            "unsafe-safety-comment/safety-comment-missing",
        );
        let v1 = DisciplineBaseline {
            version: 1,
            findings: vec![
                BaselineEntry {
                    gate: "unsafe-safety-comment".into(),
                    rule: live.title.clone(),
                    path: "src/lib.rs".into(),
                    fingerprint: fingerprint_for_version(&live, none, 1),
                },
                BaselineEntry {
                    gate: "unsafe-safety-comment".into(),
                    rule: live.title.clone(),
                    path: "src/gone.rs".into(),
                    fingerprint: "0".repeat(64),
                },
            ],
        };
        let (v2, report) = migrate(&v1, &[&live], none);
        assert_eq!(
            report,
            Migration {
                migrated: 1,
                dropped: 1
            }
        );
        assert_eq!(v2.version, FINGERPRINT_VERSION);
        assert_eq!(v2.findings, vec![entry_for(&live, none)]);
        assert_eq!(v2.findings[0].rule, live.code);
    }

    use super::*;

    #[test]
    fn record_policy_follows_what_would_block() {
        let default = RecordPolicy {
            fail_on_warnings: false,
            all_severities: false,
        };
        assert!(default.records(Severity::Error));
        assert!(!default.records(Severity::Warning));
        assert!(!default.records(Severity::Note));

        let strict = RecordPolicy {
            fail_on_warnings: true,
            all_severities: false,
        };
        assert!(strict.records(Severity::Error));
        assert!(strict.records(Severity::Warning));
        assert!(!strict.records(Severity::Note));

        let all = RecordPolicy {
            fail_on_warnings: false,
            all_severities: true,
        };
        assert!(all.records(Severity::Warning));
        assert!(all.records(Severity::Note));
    }

    #[test]
    fn severity_tally_renders_in_severity_order_with_gates() {
        let mut t = SeverityTally::default();
        assert_eq!(t.summary(), "none");
        t.add(Severity::Note, "pii");
        t.add(Severity::Warning, "pii");
        t.add(Severity::Warning, "agent-diff");
        t.add(Severity::Error, "time-estimates");
        assert_eq!(t.total(), 4);
        assert_eq!(t.summary(), "1 error, 2 warnings, 1 note");
        assert_eq!(
            t.summary_by_gate(),
            "1 error (time-estimates: 1), 2 warnings (agent-diff: 1, pii: 1), 1 note (pii: 1)"
        );
    }

    #[test]
    fn test_baseline_roundtrip() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("discipline-baseline.toml");

        let baseline = DisciplineBaseline {
            version: 1,
            findings: vec![BaselineEntry {
                gate: "time-estimates".to_string(),
                rule: "Time Estimates In Documentation".to_string(),
                path: "docs/ROADMAP.md".to_string(),
                fingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
                    .to_string(),
            }],
        };

        baseline.write_to_file(&path).unwrap();
        let loaded = DisciplineBaseline::load_from_file(&path).unwrap();
        assert_eq!(baseline, loaded);
    }

    #[test]
    fn test_fingerprint_is_line_number_independent() {
        let temp = tempfile::tempdir().unwrap();
        let file_path = temp.path().join("sample.txt");
        std::fs::write(&file_path, "\n\n   sample target line content   \n").unwrap();

        let v1 = Violation {
            gate: "pii",
            code: "pii/fixture".to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(3),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp1 = compute_violation_fingerprint(temp.path(), &v1);

        // Edit file: add 5 lines before the content
        std::fs::write(&file_path, "# Header\n# Line 2\n# Line 3\n# Line 4\n# Line 5\n\n\n   sample target line content   \n").unwrap();

        let v2 = Violation {
            gate: "pii",
            code: "pii/fixture".to_string(),
            fingerprint: String::new(),
            anchor: None,
            legacy_title: None,
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(8),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp2 = compute_violation_fingerprint(temp.path(), &v2);

        // Line number shifted from 3 to 8, but fingerprint MUST match exactly
        assert_eq!(fp1, fp2);
    }
}
