//! Grandfathering baseline mechanism for discipline findings.
//!
//! Allows teams adopting discipline on mature repositories to grandfather pre-existing
//! findings into `discipline-baseline.toml` using `discipline baseline --write`.
//! Subsequent runs report baselined findings as non-blocking notes ("N baselined findings not blocking")
//! and fail only on NEW violations.
//!
//! Fingerprints are stable and decoupled from line numbers:
//! sha256(gate + rule + path + normalized_content_hash), so unrelated line additions or deletions
//! do not churn the baseline.

use crate::guards::{GateOutcome, Violation};
use crate::report::gitlab::sha256_hex;
use anyhow::{Context as _, Result};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

pub const DEFAULT_BASELINE_FILE: &str = "discipline-baseline.toml";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct BaselineEntry {
    pub gate: String,
    pub rule: String,
    pub path: String,
    pub fingerprint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DisciplineBaseline {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub findings: Vec<BaselineEntry>,
}

fn default_version() -> u32 {
    1
}

impl Default for DisciplineBaseline {
    fn default() -> Self {
        Self {
            version: 1,
            findings: Vec::new(),
        }
    }
}

impl DisciplineBaseline {
    pub fn load_from_file(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read baseline file `{}`", path.display()))?;
        toml::from_str(&content)
            .with_context(|| format!("failed to parse baseline file `{}`", path.display()))
    }

    pub fn write_to_file(&self, path: impl AsRef<Path>) -> Result<()> {
        let path = path.as_ref();
        let mut sorted = self.clone();
        sorted.findings.sort();
        let serialized = toml::to_string_pretty(&sorted)
            .context("failed to serialize discipline baseline to TOML")?;
        let header = "# Discipline Findings Baseline\n# Generated by `discipline baseline --write`\n# Do not edit manually; commit alongside configuration changes.\n\n";
        let out = format!("{header}{serialized}");
        std::fs::write(path, out)
            .with_context(|| format!("failed to write baseline file `{}`", path.display()))?;
        Ok(())
    }
}

/// Compute a stable finding fingerprint decoupled from line numbers.
///
/// Formula: sha256(gate + ":" + rule + ":" + path + ":" + sha256(normalized_line_content))
pub fn compute_violation_fingerprint(repo_root: &Path, v: &Violation) -> String {
    let path = v.file.as_deref().unwrap_or("");
    let line_content = match (&v.file, v.line) {
        (Some(f), Some(l)) if l > 0 => {
            let full_path = repo_root.join(f);
            if let Ok(content) = std::fs::read_to_string(&full_path) {
                content
                    .lines()
                    .nth(l - 1)
                    .map(|s| s.trim().to_string())
                    .unwrap_or_else(|| v.message.trim().to_string())
            } else {
                v.message.trim().to_string()
            }
        }
        _ => v.message.trim().to_string(),
    };

    let content_hash = sha256_hex(line_content.as_bytes());
    let source = format!("{}:{}:{}:{}", v.gate, v.title, path, content_hash);
    sha256_hex(source.as_bytes())
}

#[derive(Debug, Default)]
pub struct BaselineMatchResult {
    pub baselined_count: usize,
    pub stale_count: usize,
    pub stale_by_gate: BTreeMap<String, usize>,
}

/// Match detected violations against the baseline.
///
/// Grandfathered violations are removed from `outcome.violations` and accounted for
/// in `outcome.baselined` and `outcome.notes`.
/// Stale baseline entries (entries in baseline with no matching violation in this run)
/// are reported as non-blocking notes prompting ratcheting down.
pub fn apply_baseline(
    repo_root: &Path,
    baseline: &DisciplineBaseline,
    outcomes: &mut [GateOutcome],
) -> BaselineMatchResult {
    let mut available_fps: HashMap<String, usize> = HashMap::new();
    for entry in &baseline.findings {
        *available_fps.entry(entry.fingerprint.clone()).or_insert(0) += 1;
    }

    let mut total_baselined = 0;
    let mut matched_by_entry: HashMap<String, usize> = HashMap::new();

    for outcome in outcomes.iter_mut() {
        if !outcome.enabled {
            continue;
        }

        let mut remaining_violations = Vec::with_capacity(outcome.violations.len());
        let mut gate_baselined = 0;

        for v in outcome.violations.drain(..) {
            let fp = compute_violation_fingerprint(repo_root, &v);
            if let Some(count) = available_fps.get_mut(&fp) {
                if *count > 0 {
                    *count -= 1;
                    *matched_by_entry.entry(fp).or_insert(0) += 1;
                    gate_baselined += 1;
                    total_baselined += 1;
                    continue;
                }
            }
            remaining_violations.push(v);
        }

        outcome.violations = remaining_violations;
        outcome.baselined = gate_baselined;

        if gate_baselined > 0 {
            let suffix = if gate_baselined == 1 { "" } else { "s" };
            outcome.notes.push(format!(
                "{gate_baselined} baselined finding{suffix} not blocking"
            ));
        }
    }

    let mut stale_count = 0;
    let mut stale_by_gate: BTreeMap<String, usize> = BTreeMap::new();

    let mut consumed_fps = matched_by_entry;
    for entry in &baseline.findings {
        if let Some(count) = consumed_fps.get_mut(&entry.fingerprint) {
            if *count > 0 {
                *count -= 1;
                continue;
            }
        }
        stale_count += 1;
        *stale_by_gate.entry(entry.gate.clone()).or_insert(0) += 1;
    }

    if stale_count > 0 {
        for (gate, count) in &stale_by_gate {
            if let Some(outcome) = outcomes.iter_mut().find(|o| o.gate == gate) {
                let suffix = if *count == 1 { "y" } else { "ies" };
                outcome.notes.push(format!(
                    "{count} stale baseline entr{suffix} (resolved findings): run `discipline baseline --write` to ratchet down"
                ));
            }
        }
    }

    BaselineMatchResult {
        baselined_count: total_baselined,
        stale_count,
        stale_by_gate,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Severity;

    #[test]
    fn test_baseline_roundtrip() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("discipline-baseline.toml");

        let baseline = DisciplineBaseline {
            version: 1,
            findings: vec![BaselineEntry {
                gate: "time-estimates".to_string(),
                rule: "Time Estimates In Documentation".to_string(),
                path: "docs/ROADMAP.md".to_string(),
                fingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
                    .to_string(),
            }],
        };

        baseline.write_to_file(&path).unwrap();
        let loaded = DisciplineBaseline::load_from_file(&path).unwrap();
        assert_eq!(baseline, loaded);
    }

    #[test]
    fn test_fingerprint_is_line_number_independent() {
        let temp = tempfile::tempdir().unwrap();
        let file_path = temp.path().join("sample.txt");
        std::fs::write(&file_path, "\n\n   sample target line content   \n").unwrap();

        let v1 = Violation {
            gate: "pii",
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(3),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp1 = compute_violation_fingerprint(temp.path(), &v1);

        // Edit file: add 5 lines before the content
        std::fs::write(&file_path, "# Header\n# Line 2\n# Line 3\n# Line 4\n# Line 5\n\n\n   sample target line content   \n").unwrap();

        let v2 = Violation {
            gate: "pii",
            severity: Severity::Error,
            title: "Host Leak".to_string(),
            file: Some("sample.txt".to_string()),
            line: Some(8),
            message: "leaked host".to_string(),
            remediation: None,
        };

        let fp2 = compute_violation_fingerprint(temp.path(), &v2);

        // Line number shifted from 3 to 8, but fingerprint MUST match exactly
        assert_eq!(fp1, fp2);
    }
}
